env: "local"
storage_path: "/some/path"
http_server:
  address: ":8001"
  timeout: 10
  idle_timeout: 5
database:
  host: "0.0.0.0"
  port: 5455
  username: "postgres"
  password: "postgres"
  name: "postgres"
  max_attempts: 5
auth:
  secret: "EzP1GQI3tX7dcdRy4oxvGvNKD7-8C3X8FoJZXmQcG5o="