env: "local"
storage_path: "/some/path"
http_server:
  address: "127.0.0.1:8001"
  timeout: 10
  idle_timeout: 5
database:
  host: "0.0.0.0"
  port: 5455
  username: "postgres"
  password: "postgres"
  name: "postgres"
  max_attempts: 5
