env: "local"
storage_path: "/some/path"
http_server:
  address: "0.0.0.0:8080"
  timeout: 10
  idle_timeout: 5
database:
  host: "0.0.0.0"
  port: 5435
  username: "keysheero"
  password: "keysheeropassword"
  name: "why404pg"
  max_attempts: 5
auth:
  secret: "EzP1GQI3tX7dcdRy4oxvGvNKD7-8C3X8FoJZXmQcG5o="